branch-defaults:
  Emma's_week10_branch:
    environment: LiquorlibraryV2-env
environment-defaults:
  LiquorlibraryV2-env:
    branch: null
    repository: null
global:
  application_name: liquorlibrary-v2
  default_ec2_keyname: liquorlibrary-sydney
  default_platform: arn:aws:elasticbeanstalk:ap-southeast-2::platform/PHP 7.2 running
    on 64bit Amazon Linux/2.8.12
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
